# https://starship.rs/config

format = """\
$time| \
$battery\
$memory_usage
$username$hostname\
$git_branch$git_state$git_status
$username$hostname$directory$character
"""

[time]
disabled = false
time_format = "%m.%d.%a @ %R"
style = "bold dimmed yellow"
format = "[$time]($style) "

[hostname]
format = "@[$hostname]($style) "

[aws]
symbol = " "

[battery]
charging_symbol = " "
discharging_symbol = " "
full_symbol = " "

[[battery.display]] 
threshold = 10
style = "bold red"

[[battery.display]] 
threshold = 30
style = "bold orange"

[[battery.display]] 
threshold = 51
style = "bold yellow"

[[battery.display]] 
threshold = 100
style = "bold dimmed green"

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
# always_show_remote = true
format = "[$symbol$branch]($style) ($remote_name:)$remote_branch"

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
disabled = false
threshold = 50
style = "bold dimmed yellow"
symbol = ""
format = "[$symbol ${ram_pct}]($style) "

[directory]
truncation_length = 8
truncation_symbol = "…/"
style = "dimmed bold cyan"
read_only_style = "dimmed bold red"
format = "[$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[▶]()"
error_symbol = "[▶](bold dimmed red)"

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
